[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "ai.aws.dynamodb"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Type/Connector", "Vendor/Amazon", "Area/AI & Machine Learning", "Area/Database", "Type/Short Term Memory Store", "Name/Amazon DynamoDB Short Term Memory Store"]
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.aws.dynamodb"
icon="icon.png"

[build-options]
observabilityIncluded = true
